# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'BuDeJie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.2.0'
  pod 'MJExtension', '~> 3.0.15'
  pod 'SDWebImage', '~> 4.4.0'
  pod 'SDWebImage/GIF'
  pod 'SVProgressHUD', '~> 2.2.5'

  # Pods for BuDeJie

  target 'BuDeJieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuDeJieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
